ktor:
    application:
        modules:
            - io.github.lucaswithboots.ApplicationKt.module
    deployment:
        port: 8080
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5433/pontoqr"
  user: "postgres"
  password: "senha"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"